using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HappyTechFeedback
{
    class DBHandler
    {
        private string connectionString;

        //object storing the connection to the DB
        SqlConnection connectionToDB;

        //
        private SqlDataAdapter dataAdapter;

        //custom creator
        public DBHandler(string connectionString)
        {
            this.connectionString = connectionString;
        }

        public void openConnection()
        {
            //create connection object
            connectionToDB = new SqlConnection(connectionString);

            //opens the connection
            connectionToDB.Open();
        }
        
        //closes the connection
        public void closeConnection()
        {
            connectionToDB.Close();
        }

        //returns data set generated by the sqlStatement in the parameter
        public DataSet getDataSet(string sqlStatement)
        {
            DataSet dataSet;

            //create the Data Adapter to manipulate table from DB
            dataAdapter = new SqlDataAdapter(sqlStatement, connectionToDB);

            //create the data set
            dataSet = new DataSet();
            dataAdapter.Fill(dataSet);

            return dataSet;
        }

    }
}
